name: Sync Secrets to Vercel

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync-secrets-to-vercel.yml'

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Link Vercel Project
        run: |
          vercel link --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=daniel-mcshans-projects --project=f8-slackbot
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Sync SLACK_BOT_TOKEN
        run: |
          echo "${{ secrets.SLACK_BOT_TOKEN }}" | vercel env add SLACK_BOT_TOKEN production --token=${{ secrets.VERCEL_TOKEN }} || echo "Already exists"

      - name: Sync SLACK_SIGNING_SECRET
        run: |
          echo "${{ secrets.SLACK_SIGNING_SECRET }}" | vercel env add SLACK_SIGNING_SECRET production --token=${{ secrets.VERCEL_TOKEN }} || echo "Already exists"

      - name: Sync OPENROUTER_API_KEY
        run: |
          echo "${{ secrets.OPENROUTER_API_KEY }}" | vercel env add OPENROUTER_API_KEY production --token=${{ secrets.VERCEL_TOKEN }} || echo "Already exists"

      - name: Sync PLATFORM_GATEWAY_URL
        run: |
          echo "${{ secrets.PLATFORM_GATEWAY_URL }}" | vercel env add PLATFORM_GATEWAY_URL production --token=${{ secrets.VERCEL_TOKEN }} || echo "Already exists"

      - name: Summary
        run: |
          echo "✅ Secrets synced to Vercel!"
          vercel env ls --token=${{ secrets.VERCEL_TOKEN }}

